### ISSUE TITLE
Add more data sources

### ISSUE THREAD

**Issue by welcoMattic** [jolicode/starfleet#5]
## Todo:

- [x] Create FetcherInterface
- [x] Implement this interface to create a fetcher for https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2019/php.json
- [x] Modify the command `starfleet-conferences-fetch` to let it call the fetcher
- [x] Compute a hash from conference.slug (cleaned: remove year for instance)+conference.startAt+conference.endAt to check if we already have the conference in database
- [x] The fetcher `fetch` method must return an array of Conference entities
- [x] Save conferences in database

We will improve fetchers with other sources in near future.

---
## Help

See:

- https://github.com/tech-conferences/conference-data
- http://api.joind.in/

**Comment by damienalexandre** [comment]
Not easy to automate: https://github.com/lauthieb/awesome-cfp
